### ISSUE TITLE
Cannot find module "react/lib/ReactDOM"

### ISSUE THREAD

**Issue by cxylys** [rsuite/rsuite-table#10]
![image](https://user-images.githubusercontent.com/3087711/30241991-7d71f9dc-95c0-11e7-89fe-732ae2014ade.png)
在安装了rsuite-table在文件里引用后报这个错误

**Comment by simonguo** [comment]
@cxylys  把你 package.json 配置我看一下

**Comment by cxylys** [comment]
![image](https://user-images.githubusercontent.com/3087711/30242110-f1f8b154-95c2-11e7-9561-a222732cb25f.png)
配置为这样

**Comment by simonguo** [comment]
```js
install i  rsuite@2.0.0-alpha-2  
```
试一下

**Comment by cxylys** [comment]
重新装了这个版本的好了,另外再请问下目前这个是还不支持移动端的滚动嘛?
![image](https://user-images.githubusercontent.com/3087711/30242306-8baf433c-95c6-11e7-9188-f60b8c9107f2.png)
我x,y 都没反应

**Comment by simonguo** [comment]
@cxylys  这个 table 主要是为了 企业级后台管理做的，移动端还存在一些问题。 移动端近期我会看一下，如果方便的话，考虑做一下适配。

**Comment by cxylys** [comment]
好的,知道了。感谢你的帮助。

**Comment by simonguo** [comment]
@cxylys  适配移动端，试一下这个版本：
```
rsuite-table@2.0.1-beta.1
```

**Comment by cxylys** [comment]
好的,我先试试。感谢！
