### ISSUE TITLE
TypeError: Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by tangshuang** [rsuite/rsuite-table#11]
报如题错，查了一下，是因为react.PropTypes已经deprecated了。希望能重新调整一下组件的依赖。

**Comment by simonguo** [comment]
@tangshuang  你试一下这个版本： `rsuite-table@2.0.1-beta.5`

**Comment by tangshuang** [comment]
@simonguo 我自己fork了一个，使用的时候我有个感觉，就是渲染的时候界面卡顿，这个感觉是最大的问题，不知道能不能优化一下？

**Comment by simonguo** [comment]
@tangshuang
你能描述详细一些嘛，具体是哪里卡顿？
