### ISSUE TITLE
功能请求：虚拟table渲染和换行不能共存

### ISSUE THREAD

**Issue by zxyling** [rsuite/rsuite-table#111]
virtualized={true}， wordWrap这两个属性同时存在的时候，虚拟渲染被自动关掉，请问这个有什么解决方案么

**Comment by simonguo** [comment]
@zxyling  暂时无解，wordWrap 的实现方式是通过内容渲染后，然后在去获取所有渲染完成的 Cell 的 height, 最后再重新把一行中 Cell height 最大值设置给 Row。

而设置 virtualized 后，渲染的 Row 只是 data 中的一部分，如果采用同样的方式会导致 virtualized 中的 Row top 值计算存在问题，另外一个重复渲染带来的性能问题。

虽然，不能同时支持 virtualized 与 wordWrap， 但是业务中可以通过 `setRowHeight` 自定义通过rowData 中的数据来判断每一行的行高
```ts
setRowHeight: (rowData:object)=> number
```
