### ISSUE TITLE
功能请求：横向滚动加入虚拟渲染

### ISSUE THREAD

**Issue by zxyling** [rsuite/rsuite-table#113]
请问有没有后续增加table横向滚动增加虚拟渲染的计划，在使用中有列特别多的情况，目前table只做了竖向的虚拟渲染，这种情况下，渲染的dom量依然很大，上下滑动中有一些卡顿现象。不知道后续有没有这方面的计划。

**Comment by simonguo** [comment]
@zxyling  暂时没有提供横向 virtualized 的计划，我认为你卡顿的瓶颈不在横向 virtualized 能够解决问题， 能否提供一下 codesandbox 示例，我们看一下，具体问题具体分析。

**Comment by zxyling** [comment]
https://codesandbox.io/embed/confident-gould-l6cjg?fontsize=14&hidenavigation=1&theme=dark
麻烦看下，就是这个卡顿

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/70289913-420ed380-1811-11ea-9f8a-45bfd4e89a28.png)
@zxyling  你提供的示例没有复现你描述的问题，是不是示例代码没有成功上传？

**Comment by zxyling** [comment]
https://codesandbox.io/s/confident-gould-l6cjg?fontsize=14&hidenavigation=1&theme=dark
你看的那个链接不对，看下我发的这个链接

**Comment by simonguo** [comment]
看到了，确实有卡顿现象，我研究一下，看看怎么改善。

**Comment by zxyling** [comment]
👌，我这边也在查这个原因，初步怀疑是因为我在代码中动态生成了Column及Cell部分，导致每次滚动触发重绘，通过性能分析后发现有滚动时候有多个task

**Comment by simonguo** [comment]
调整以下两点会有所改善：

1. 为 `<Table>` 添加 `rowKey` 属性，例如：

```jsx
<Table data={data} rowKey="id">
```
> `id` 对应 data 中每一行数据的唯一值。

2. 调整 Table 的 height, 尽量让 height 值小，这样在设置 virtualized 以后，可视范围内的 HTML 元素渲染也相对较少。

示例：  https://codesandbox.io/s/admiring-mclean-mjpvm

**Comment by zxyling** [comment]
height这个因为产品需求不太能够搞定，rowkey可以试试
刚才用chrome 分析了下 整个table 会因为滚轮 整个重绘
你可以看看。

**Comment by simonguo** [comment]
你说到产品需求，我觉得你们的产品设计也是奇葩，设计了一个有 50 列的表格。

如果非要在表格中显示这么多列，从易用性上考虑，你需要在表格的头部添加一个可以筛选列的控件，默认显示常用的列，然后可以让用户可以自定显示需要展示的列。 类似如下图：

![WechatIMG7](https://user-images.githubusercontent.com/1203827/70309465-92555800-1848-11ea-9b66-b7ead6450b0b.png)

如果做的更方便点，可以再提供一个 Excel 导出。

**Comment by fallenleavesguy** [comment]
插个楼，我们也需要横向虚拟滚动。我们的情况不同，没办法设置只显示某些列。我们的需求是股市软件常见的情况。从左到右，每一列一年或者一个月的数据总结，一直往右，数据越看越旧，很难在设置上界定只显示某些列。主要是股市软件上有这个操作的界面实在太常见了。现在我们是自己临时写的简单版

**Comment by coder666666** [comment]
@fallenleavesguy 我也遇到了这样的情况，我们确实是客户要求奇葩，目前相对保守的情况下都有120列了，react确实没有找到支持横向虚拟滚动的组件，不过找到了一个vue的，效果看demo确实不错的，可以借鉴一下：[http://www.umyui.com/umycomponent/columnsAndRows](http://www.umyui.com/umycomponent/columnsAndRows)
