### ISSUE TITLE
可以横向滚动的表格滑到底后依然能滑

### ISSUE THREAD

**Issue by wickedcode01** [rsuite/rsuite-table#114]
会划出一大堆空白。 采用的autoheight。

**Comment by simonguo** [comment]
@wickedcode01  使用的什么版本？

请使用 https://codesandbox.io/ 复现一下你的问题

**Comment by wickedcode01** [comment]
> @wickedcode01 使用的什么版本？
> 
> 请使用 https://codesandbox.io/ 复现一下你的问题

目前github上这个版本。我直接build的。复现方法。直接autoheight,然后写5个column,宽度设置100（超过屏幕宽度就行），chrome切换手机模式，一直往下拖动。

**Comment by wickedcode01** [comment]
发现不需要左右滚动的表格，任何表格都能复现。前提是autoheight.

**Comment by wickedcode01** [comment]
一定要用手机模式，用鼠标拖动，而不是滚轮滑。滚轮滑是没正常的。

**Comment by simonguo** [comment]
@wickedcode01  好的，应该是一个小问题，我处理下。 不过 rsuite-table 我们更推荐只在桌面浏览器使用。
