### ISSUE TITLE
边框被遮挡，看不见。

### ISSUE THREAD

**Issue by wickedcode01** [rsuite/rsuite-table#115]
采用的绝对定位，y轴没有加上边框的宽度。会遮挡住边框。

**Comment by simonguo** [comment]
请使用图片示例，或者提供 https://codesandbox.io/ 示例说明。

**Comment by wickedcode01** [comment]
这个问题我通过改源码解决了。autoheight的情况下，因为这个问题，还会导致实际高度高出一截，因为边框被重叠了，实际高度变低了。
