### ISSUE TITLE
排序功能图标切换异常

### ISSUE THREAD

**Issue by wickedcode01** [rsuite/rsuite-table#119]
可以排序的列，第一次点击图标是可以正常变化的。但是第二次点击就不会变了。在Headercell组件里console后发现第二次点击以后就没有收到props。查了源码很久，没找到原因。

**Comment by wickedcode01** [comment]
https://codesandbox.io/s/jovial-williamson-5l4d5?fontsize=14&hidenavigation=1&theme=dark
在这个沙盒里面，貌似图标一次都变不了。

**Comment by simonguo** [comment]
@wickedcode01  排序的属性是受控的，你需要在改变状态后去设置排序 sortColumn 与 sortType

```jsx
const [sortColumn, setSortColumn] = React.useState("name");
const [sortType, setSortType] = React.useState("desc");

<Table
  sortColumn={sortColumn}
  sortType={sortType}
  onSortColumn={(columnName, type) => {

    /**  ...省略异步去处理数据逻辑  **/

    // 更新排序的列名
    setSortColumn(columnName);
    // 设置顺序，还是倒序
    setSortType(type);
  }}
>
```

**Comment by wickedcode01** [comment]
@simonguo 

我在GitHub上build的这个版本，只需要在onSortColumn里setState一下，触发render，然后就能切换图标了。以至于我只需要这样写
<Tabel sortColumn={this.state.col}  onSortColumn={(key,type)=>this.setState({col:key})}...>
就能任意切换排序。

沙盒里从npm下的那个版本却不行。

**Comment by simonguo** [comment]
@wickedcode01   https://codesandbox.io/s/eloquent-fog-t52f3  这不是可以吗？

**Comment by wickedcode01** [comment]
@simonguo 知道了。
