### ISSUE TITLE
table怎么实现2维表格

### ISSUE THREAD

**Issue by puchenhui** [rsuite/rsuite-table#122]
横向跟纵向都有表头，应该怎么实现，官方api没有写，大佬们应该怎么实现

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/71472274-5ab94a80-280d-11ea-9d55-037eae911c70.png)
你是想这样锁定列？

**Comment by puchenhui** [comment]
![微信截图_20191226183346](https://user-images.githubusercontent.com/28975452/71472510-445fbe80-280e-11ea-948e-750a18b81adf.png)
是这种样子  我随便画的

**Comment by simonguo** [comment]
@puchenhui  锁定列就可以实现啊。
手机、平板、电池、显示器作为 “类别” 这一列的数据
