### ISSUE TITLE
功能请求：表头高度和排序问题

### ISSUE THREAD

**Issue by Mr-amw** [rsuite/rsuite-table#131]
1、在wordWrap和resizable同时设置时，高度没变导致内容显示不全 
2、排序不能指定某列默认正序或倒序排列
@simonguo

**Comment by simonguo** [comment]
1. wordWrap 的实现是等 Table 单元格渲染完了以后，再获取单元格的高度进行对比，重新生成新的高度，会存在两次渲染的，所以没有特殊业务要求尽量少用，目前是会在表格大小变化和数据更新后会重新计算高度。针对你的问题后续我看看怎么改进一下。
2.排序的功能你可以通过 Table 的 `sortColumn`与 `sortType` 属性设置。
