### ISSUE TITLE
wordWrap is not working if virtualized is set to true

### ISSUE THREAD

**Issue by ZyrusReyes** [rsuite/rsuite-table#134]
**wordWrap=true, virtualized=false**
<img width="1188" alt="Screen Shot 2020-03-12 at 9 56 38 AM" src="https://user-images.githubusercontent.com/49890815/76479945-5550c100-6448-11ea-866e-1ee53aea9f0d.png">

**wordWrap=true, virtualized=true**
<img width="1189" alt="Screen Shot 2020-03-12 at 9 56 26 AM" src="https://user-images.githubusercontent.com/49890815/76479996-70bbcc00-6448-11ea-833c-61c1ba76fd57.png">

**Comment by simonguo** [comment]
@ZyrusReyes 

The implementation of the wordWrap property in the table is to let the component render to the DOM, and then re-render the cell height after getting the actual height of the DOM.

Then the `virtualized` property is to avoid unnecessary component rendering. So `wordWrap` and` virtualized` cannot be used together. Sorry, the relevant instructions are missing from the documentation.

**Comment by ZyrusReyes** [comment]
Thanks @simonguo
