### ISSUE TITLE
滚动条拖动事件BUG

### ISSUE THREAD

**Issue by peakandyuri** [rsuite/rsuite-table#14]
Table组件自己实现了一个滚动条样式，但是事件监听不正确，应该使用document.addEventListener来监听，这样即使鼠标移到了浏览器窗体外，仍然能继续响应事件，现在是我拖动“滚动条”的时候，鼠标到浏览器之外松开鼠标再回到页面上，滚动条仍属于拖动状态，会随鼠标滚动。另外默认滚动条样式非常丑，webkit内核可以通过CSS修改滚动条样式，有时候喜欢自己去改，希望能有个配置启用或禁用组件实现的滚动条样式。
重现页面：https://rsuitejs.com/rsuite-table/#%E5%88%86%E9%A1%B5

**Comment by simonguo** [comment]
@peakandyuri  这里的滚动条非浏览器原生的，是通过html元素模拟的滚动条，目的是为了解决table锁定列遇到的问题：http://blog.hypers.io/2017/09/03/rsuite-table/#%E9%94%81%E5%AE%9A%E5%88%97 。

关于你提到的滚动不能在浏览器窗体外响应的问题，我们会在最近的版本中会修复。
