### ISSUE TITLE
[Feature request] Selectable out of the box

### ISSUE THREAD

**Issue by ButuzGOL** [rsuite/rsuite-table#147]
i would be great to have this feature without custom cell

**Comment by simonguo** [comment]
Can you elaborate on your request?

**Comment by ButuzGOL** [comment]
as i see https://rsuitejs.com/en/components/table
=> "Custom Cell" gives example of Selectable behaviour with logic 
```
this.handleCheckAll = this.handleCheckAll.bind(this);
this.handleCheck = this.handleCheck.bind(this);
```
but i think it would be good if it would be out of the box

**Comment by simonguo** [comment]
hi @ButuzGOL 
Tables are designed to strike a balance between usability and scalability.
You can refer to the following examples, which contain common scenarios for custom units.
https://rsuite.github.io/rsuite-table/#8

Please upgrade to the latest rsuite-table. The issue will be closed. If you have new requirements, please open a new issue.
