### ISSUE TITLE
[Feature request] Nested headers with resize/sort abilities

### ISSUE THREAD

**Issue by ButuzGOL** [rsuite/rsuite-table#148]
Any plans for such feature ?

**Comment by simonguo** [comment]
Table currently supports resizing and sorting of grouped table headers. You may not have reviewed the documentation carefully.

Refer to this document: https://rsuitejs.com/en/components/table

**Comment by ButuzGOL** [comment]
As i understand this 
https://rsuitejs.com/en/components/table
=> "Colspan" example 
is working with resizing and sorting ?

**Comment by simonguo** [comment]
Please upgrade to the latest version of rsuite-table.
Reference example: https://rsuite.github.io/rsuite-table/#17
