### ISSUE TITLE
[Feature request] Drag rows

### ISSUE THREAD

**Issue by ButuzGOL** [rsuite/rsuite-table#149]
If several new features will be implemented this table can be close to ag-grid )

**Comment by simonguo** [comment]
Draggable table realized by combination of `rsuite-table` and `react-dnd`
https://github.com/rsuite/rsuite-table/blob/master/docs/md/DraggableTable.md

Preview (last example):
http://rsuite.github.io/rsuite-table/

**Comment by simonguo** [comment]
Reference example: https://codesandbox.io/s/rsuite5-table-with-react-dnd-16o4n
