### ISSUE TITLE
分页组件样式引用的BUG

### ISSUE THREAD

**Issue by peakandyuri** [rsuite/rsuite-table#15]
引用了index.less之后，分页组件并没有CSS被应用到，通过查看官网上的css发现，而是采用了类似bootstrap之类的分页组件样式，我引入一个bootstrap的外链，显示就正常了，虽然和表格主题并不搭配。

**Comment by hiyangguo** [comment]
分页控件样式使用的是`rsuite-theme@2.0`版本，cdn 地址
```
https://unpkg.com/rsuite-theme@2.0.19/dist/css/rsuite.min.css
```
或者参照 [RSUITE官网](https://rsuitejs.com/getting-started)主题相关章节。
如需定制主题，可参考官网[详细说明](https://rsuitejs.com/components/theme)

**Comment by simonguo** [comment]
@peakandyuri  你好，  TablePagination 组件中依赖的 rsuite 的 Pagination 组件，所有再使用的过程中，需要安装 `rsuite-theme`.

```sh
npm  install rsuite-theme  
```

在你引入 table 样式的地方同时引入：

```css
@import "~rsuite-theme/dist/less/rsuite";
```

关于这里使用上的不方便，我们会在最新的一个版本中解决，谢谢你的支持。
