### ISSUE TITLE
树形表格，数据量大时，渲染速度过慢

### ISSUE THREAD

**Issue by hgaozhanqiang** [rsuite/rsuite-table#156]
树形表格在渲染数据的时候，数据量大，会等待很长时间才能渲染出来，我测试的数据量位600条记录，渲染时间大概5-6S

**Comment by simonguo** [comment]
参考这个 Tree 示例 2w 行左右数据:  https://rsuite.github.io/rsuite-table/#11 
示例代码:  https://github.com/rsuite/rsuite-table/blob/master/docs/md/BigTreeTable.md
