### ISSUE TITLE
Getting issues Accessing Nested Properties

### ISSUE THREAD

**Issue by MosesWakanyi** [rsuite/rsuite-table#158]
Hello,

This property seems not to work now. What has changed?

<Column width={200} fixed sortable>
            <HeaderCell>Product Name</HeaderCell>
            <Cell dataKey="product.product_name" />
 </Column>

**Comment by Gomez** [comment]
Same here, was it working before? Tested with 3.4.x, but still the same.

Here is my code 

        <Cell dataKey="node.name" />


data:

```
          "node": {
            "id": "174692e2-1f76-5fc2-9b78-4b155314c7b2",
            "name": "Accessibility",
            "version": "1.5.0",
            "desc": "Provides multiple accessibilities options to ease your use of nextcloud.",
            "added": false,
            "updated": false
          }
        },
        {
          "node": {
            "id": "b4f5c18e-30cc-5f2e-b0a4-c058f3dd2e3c",
            "name": "Activity",
            "version": "2.12.0",
            "desc": "Provides an activity feed showing your file changes and other interesting things going on in your Nextcloud.",
            "added": false,
            "updated": false
          }
        },

```

**Comment by MosesWakanyi** [comment]
Forced to use this, wondering whether it's efficient!
            Cell>
              {(rowData, rowIndex) => {
                return rowData.node.name;
              }}
            </Cell>

**Comment by simonguo** [comment]
Currently does not support the nested properties.
@MosesWakanyi  The solution you use is effective.

```tsx
<Column width={200}>
  <HeaderCell>Name</HeaderCell>
  <Cell>{rowData => rowData.node.name}</Cell>
</Column>
```

**Comment by Gomez** [comment]
Thanks works. Added a note in the readme: https://github.com/rsuite/rsuite-table/pull/159

**Comment by axtscz** [comment]
This workaround no longer appears to be working
