### ISSUE TITLE
Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefined

### ISSUE THREAD

**Issue by xiangjiayu** [rsuite/rsuite-table#16]
Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefined
一直报这个错误 。找了好久资料 。还是没解决 。

**Comment by simonguo** [comment]
@xiangjiayu  你用的那个版本？ 你看一下你的 dom-lib 用的那个版本？

**Comment by xiangjiayu** [comment]
dom-lib  ？
怎么查看的 。因为我不知道你说的是想看哪个版本 。

**Comment by xiangjiayu** [comment]
"rsuite": "^2.1.3",
 "rsuite-table": "^2.1.4",

**Comment by simonguo** [comment]
@xiangjiayu  你用什么浏览器？

**Comment by xiangjiayu** [comment]
chrome  我是要做一个移动端的项目 要用到滚动的表格。本来项目都是基于antd mobile,
奈何它移动端没有table啊

**Comment by simonguo** [comment]
这个版本没发现你说的这个问题，你尝试安装一下  dom-lib
```
npm install dom-lib@0.2.6  
```

**Comment by xiangjiayu** [comment]
ok 我试试 。

**Comment by xiangjiayu** [comment]
还是没搞定 。我明天再问问。再看看资料。谢谢你了。这么晚还帮忙看问题。再次感谢。

**Comment by simonguo** [comment]
好的，你明天可以看下 https://rsuitejs.com/rsuite-table/ 在你浏览器上是否存在同样的错误，如果访问正常，可以参考一下这个网站的配置。

**Comment by simonguo** [comment]
@xiangjiayu  https://github.com/KyleAMathews/element-resize-event/issues/29

**Comment by hustcc** [comment]
可以换成我这边重写的 [size-sensor](https://github.com/hustcc/size-sensor)。代码更清晰一些，[echarts-for-react](https://github.com/hustcc/echarts-for-react) 也切换了！
