### ISSUE TITLE
单独使用rsuite-table,丢失了排序样式

### ISSUE THREAD

**Issue by aierweisi** [rsuite/rsuite-table#161]
![image](https://user-images.githubusercontent.com/33406910/90376702-75487880-e0a9-11ea-96f5-e3ef90ace523.png)

**Comment by simonguo** [comment]
没有样式丢失，rsuite-table 中的排序字符就是这样。 

- 如果你想换掉可以，可以覆盖 .rs-table-cell-header-icon-sort::after 的 content
![image](https://user-images.githubusercontent.com/1203827/90404634-3fb98480-e0d5-11ea-872a-4d355cdf53a4.png)
- 或者自定义 HeaderCell
