### ISSUE TITLE
另外，当开启虚拟滚动时，表格高度必须固定嘛？能不能根据内容来展示

### ISSUE THREAD

**Issue by aierweisi** [rsuite/rsuite-table#162]

**Comment by simonguo** [comment]
virtualized 的实现原理是通过固定容器高度与行高，计算滚动距离，渲染出可视范围内的数据。 肯定是要定高。

你想要根据内容展示，内容不多的情况下为什么要用 virtualized 呢？

另外，Table 的高度你是可以自己去计算容器高度，然后再为其赋值，[参考](https://github.com/rsuite/rsuite-management-system/blob/master/src/routes/list/members/DataTable.js#L70)。
