### ISSUE TITLE
开启虚拟化和关闭shouldUpdateScroll后，会出现页面栈溢出的React报错

### ISSUE THREAD

**Issue by begoat** [rsuite/rsuite-table#163]
> 已经是最新的rsuite(4.8.1)和react(16.13.1)了

* 业务需求：
前端拿到所有的数据(8k), 然后进行各种filter控制筛选，改变传给table的data

* bug复现：
https://codesandbox.io/s/rsuite-hello-world-20-forked-1um9o?file=/src/index.js
```jsx
<Table
  virtualized={true}
  shouldUpdateScroll={false}
  data={改变}
 >...</Table>
```
1. 按照这样的参数去传给table
2. 下拉滚动条到某个位置
3. 触发data改变
4. bug复现 页面崩溃 Maximum update depth exceeded

* 复现视频：
https://william-test-1252077334.cos.ap-shanghai.myqcloud.com/rsuite-table-crash.mov

**Comment by begoat** [comment]
@simonguo  暂时通过shouldUpdateScroll={true} 避免了问题

**Comment by LuHaikun** [comment]
这个问题有人解决了吗，我也遇到了

**Comment by simonguo** [comment]
@LuHaikun  @begoat 
Update to  `rsuite-table@3.13.2`
