### ISSUE TITLE
页面崩溃 Maximum update depth exceeded

### ISSUE THREAD

**Issue by LuHaikun** [rsuite/rsuite-table#166]
已经是最新的rsuite(4.8.1)和react(16.13.1)了

业务需求：
前端拿到所有的数据(8k), 然后进行各种filter控制筛选，改变传给table的data

bug复现：
https://codesandbox.io/s/rsuite-hello-world-20-forked-1um9o?file=/src/index.js

<Table
  virtualized={true}
  shouldUpdateScroll={false}
  data={改变}
 >...</Table>
按照这样的参数去传给table
下拉滚动条到某个位置
触发data改变
bug复现 页面崩溃 Maximum update depth exceeded
复现视频：
https://william-test-1252077334.cos.ap-shanghai.myqcloud.com/rsuite-table-crash.mov

**Comment by simonguo** [comment]
相同的问题: https://github.com/rsuite/rsuite-table/issues/163

**Comment by LuHaikun** [comment]
感谢
