### ISSUE TITLE
设置rowKey无效

### ISSUE THREAD

**Issue by LuHaikun** [rsuite/rsuite-table#171]
react_devtools_backend.js:2273 Warning: Each child in a list should have a unique "key" prop.
表格还是会报该警告

**Comment by simonguo** [comment]
设置 rowKey 以后
1.data 对应的 字段有值吗？
2.data 对应的 字段的值唯一吗？

**Comment by LuHaikun** [comment]
> 设置 rowKey 以后
> 1.data 对应的 字段有值吗？
> 2.data 对应的 字段的值唯一吗？

初始化的时候dataSource是一个空数组，查询之后才有值

**Comment by simonguo** [comment]
你在检查一下，确定是个空数组吗？  你可以通过 codesandbox 复现一下你的问题。
