### ISSUE TITLE
表格初始化的时候无数据时感官上比较突兀，希望可以优化一下

### ISSUE THREAD

**Issue by LuHaikun** [rsuite/rsuite-table#172]
![image](https://user-images.githubusercontent.com/16951645/95812536-3866ce00-0d48-11eb-8b9c-8f39b656869a.png)
表格初始化的时候无数据时可以添加一个转场前的无数据提示，感觉用户体验会友好点
![image](https://user-images.githubusercontent.com/16951645/95812656-7cf26980-0d48-11eb-8b43-acb608b150c0.png)

**Comment by simonguo** [comment]
文档中有，并且可以通过 locale 属性中的 emptyMessage 自定义， 支持 React.ReactNode。
 https://github.com/rsuite/rsuite-table/blob/master/src/Table.tsx#L161
![image](https://user-images.githubusercontent.com/1203827/95812827-deb2d380-0d48-11eb-8c33-f3cc25b9d73b.png)
http://rsuite.github.io/rsuite-table/

**Comment by LuHaikun** [comment]
> 文档中有:
> 可以通过 renderEmpty 自定义显示内容: renderEmpty?: (info: React.ReactNode) => React.ReactNode
> 
> ```tsx
> <Table
>   data={[]}
>   renderEmpty={() => {
>     return <div className="rs-table-body-info">数据为空 </div>;
>   }}
> >
> ...
> </Table>
> ```
> 
> https://github.com/rsuite/rsuite-table/blob/master/src/Table.tsx#L161
> ![image](https://user-images.githubusercontent.com/1203827/95812827-deb2d380-0d48-11eb-8c33-f3cc25b9d73b.png)
> http://rsuite.github.io/rsuite-table/

找到了。我的错没有注意到
