### ISSUE TITLE
表格虚拟滚动大数据量下滚动时内存增加导致浏览器崩溃

### ISSUE THREAD

**Issue by HuLike** [rsuite/rsuite-table#176]
开启虚拟滚动，3000条数据，列数在5、60列。 慢慢滚动到底部，内存能从70M 到4、500M。电脑内存小一点浏览器就会奔溃。
请问大佬有什么优化方法吗？

**Comment by simonguo** [comment]
访问 http://rsuite.github.io/rsuite-table/ 第一个 Virtualized 示例， 10000条数据，在你电脑上是否存在同样的问题？

**Comment by HuLike** [comment]
你好。
https://codesandbox.io/s/elegant-keldysh-kizy0?file=/src/index.js
扩展到5、60列 滚动起来内存就飙升了，这个是在线demo，可以观察memory , 2m+ 飙升。

**Comment by HuLike** [comment]
官网demo一样的 ，会一直涨 ，基本不释放。还有为啥横向滚动条没啦。。
![image](https://user-images.githubusercontent.com/72792906/95936488-45e38d00-0e08-11eb-91ae-c05b23176880.png)

**Comment by HuLike** [comment]
![image](https://user-images.githubusercontent.com/72792906/96061790-ac2ee500-0ec6-11eb-964d-10c068ada306.png)
![image](https://user-images.githubusercontent.com/72792906/96061813-bea91e80-0ec6-11eb-8cef-bcecd2d3309c.png)

**Comment by gxc685** [comment]
@simonguo 
我也遇到了同样问题但是解决方法有瑕疵，需要大佬看看
方法一：固定row key `
      if ((isUncertainHeight && virtualized) || !virtualized) {
        let j
        for (let index = 0; index < data.length; index++) {
          j++

          const rowProps = {
            key: j,
            top,
            width: rowWidth,
            depth,
            height: nextRowHeight,
          };
`
办法二： `  renderTableBody(bodyCells: any[], rowWidth: number) {
    this.tableRows = {};`

方法一不合代码直觉。
方法二会导致界面多个table的时候内存回收慢。

**Comment by simonguo** [comment]
请升级到最新版本 `rsuite-table@latest` ，性能上进行了优化。
