### ISSUE TITLE
Module not found: Error: Can't resolve '~rsuite-table/lib/less/index.less' in 

### ISSUE THREAD

**Issue by sunnycn2013** [rsuite/rsuite-table#18]
ERROR in ./src/index.jsx
Module not found: Error: Can't resolve '~rsuite-table/lib/less/index.less' in '/Users/ccguo/Documents/ETH/Demo/src'
 @ ./src/index.jsx 23:0-44
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.jsx
Child html-webpack-plugin for "index.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 861 bytes {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by sunnycn2013** [comment]
master 分支代码

**Comment by simonguo** [comment]
@sunnycn2013  

如果1： 用 npm 或者 yarn 安装， less 的目录肯定是存在的。
https://www.jsdelivr.com/package/npm/rsuite-table?path=lib%2Fless

你可以尝试重新安装一下
```
npm install rsuite-table
```

如果2：你是下载源码在本地运行
默认是没有 lib 目录，你可以把 less 目录指向到 src/less/index.less 目录

## 推荐：

推荐是 rsuite 3.0  , 可以直接使用 Table.

安装：
```sh
npm install rsuite
```
使用：
```
import { Table } from 'rsuite';

import 'rsuite/styles/less/index.less';
```
详细文档：
https://rsuitejs.com/components/table
