### ISSUE TITLE
功能请求：表格列的sort和drag功能可以同时支持吗？

### ISSUE THREAD

**Issue by webb01** [rsuite/rsuite-table#181]
设置表格列的拖拽发现就设置不了列的排序功能了，目前是否支持列的拖拽排序功能混合一起用？ @simonguo

**Comment by simonguo** [comment]
拖拽是通过 react-dnd 去自定义处理的，你如果需要同时支持拖拽排序和点击列的排序，也是可以自定义。

为 Column  设置 sortable 属性。
```tsx
<Column  sortable>
```
在 HeaderCell 中的元素就不能撑满容器了，如果撑满了就看不到排序的 icon。
你尝试把  HeaderCell 的 div 改为 span , 应该就能看到排序的 icon 了，具体样式上的细节需要你自己调整。
