### ISSUE TITLE
Variable @H500 is undefined

### ISSUE THREAD

**Issue by sweetStreet** [rsuite/rsuite-table#19]
请问这是什么原因呀
./node_modules/rsuite-table/lib/less/index.less
Module build failed: 

@pagination-background: #f5f5f5;
@resize-mouse-color: @H500;
                   ^
Variable @H500 is undefined
      in ***(项目路径名)/node_modules/rsuite-table/lib/less/variables.less (line 6, column 21)

**Comment by simonguo** [comment]
@sweetStreet 

你好， rsuite-table 中依赖的 rsuite-theme ， 默认情况下我们没有按照，你如果想要单独使用 rsuite-table 的，尝试安装一下 rsuite-theme。  

```
npm install  rsuite-theme@2.0.17 --save 
```

rsuite-table 只作为 rsuite 的一个扩展组件，个人建议你在 rsuite 中使用。

```
import { Table } from 'rsuite';
```
文档说明： https://rsuitejs.com/components/table

**Comment by sweetStreet** [comment]
谢谢！
