### ISSUE TITLE
Support Custom Minimum Width for Column Resizing

### ISSUE THREAD

**Issue by trondpet** [rsuite/rsuite-table#196]
First off thanks for a great table component. I really like the API as well as the built-in features.

For tables built on top of rsuite-table we make use of custom styling as well as custom cell renderers and content. The extensibility is great. For our use cases, which include column resizing, allowing resizing all the way down to `20px` doesn't make much sense though.

It would be great if:
a) `ColumnResizeHandler` would honor a `Column`'s `minWidth` prop when such has been provided on the `Column`, or 
b) `Column` (or alt. `Table`) could support a prop specifying the min width for resizing

both a) and b) would be replacing the [hard-coded 20px](https://github.com/rsuite/rsuite-table/blob/master/src/ColumnResizeHandler.tsx#L56) that is currently used in `ColumnResizeHandler`

a) would alter existing functionality a bit -- for implementations using a combination of `minWidth` and `resizable`, but seems, AFAICT, like a reasonable expectation for consumers of the table. If that is unacceptable, it'd be great if you would consider b). 

I'd be happy to provide a PR for either solution.

**Comment by trondpet** [comment]
@simonguo Is the above something that could be considered? We can of course alternatively implement our own resize logic  to accomplish the same, but thought it might be a reasonable expectation with regards to built-in resize behavior. As mentioned i'd be happy to PR either solution.

**Comment by simonguo** [comment]
Thank you very much for your support of `rsuite-table`. I would be happy to receive your PR for this solution.
