### ISSUE TITLE
Show/ Hide Columns

### ISSUE THREAD

**Issue by adventurini** [rsuite/rsuite-table#197]
### What problem does this feature solve?

Create the ability to show and hide columns via a dropdown selector.

**Comment by trondpet** [comment]
I'd recommend doing this outside the table and simply render the table/columns you need based the state of your application.

Example:

```
const [visibleColumns, setVisibleColumns] = useState([])

// Component(s) that what columns are visible

<Table>
   { visibleColumns.map(c => <Column key=....>...</Column>) }
</Table>
```
