### ISSUE TITLE
sortColumn not getting fired in Gatsby production build

### ISSUE THREAD

**Issue by sirrodgepodge** [rsuite/rsuite-table#199]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `16.13.1` |
| `rsuite-table` | `3.14.0` |
| `gatsby` | `2.32.3` |

### What is the expected behavior?

Clicking the column header would toggle sorting (ascending <> descending as per usual).

### What is the current behavior?

Clicking the column header in a production build of Gatsby does nothing (click handler seems to not be being fired).  I actually cannot even get a breakpoint to hit in `handleClick` in the `HeaderCell.tsx` component:
https://github.com/rsuite/rsuite-table/blob/master/src/HeaderCell.tsx

### What are the steps to reproduce?

similar to this issue https://github.com/rsuite/rsuite-table/issues/160, locally with `gatsby develop` the toggling of sorting of a column by clicking the the column header works, however with `gatsby build` it does not.

Unfortunately I cannot easily give you a codesandbox as it would require a production gatsby build (I don't think possible there), but hopoefully this is pretty straightforward to reproduce.

**Comment by sirrodgepodge** [comment]
For anyone who may come across, I've posted a $500 bounty here:
https://www.bountysource.com/issues/96980584-sortcolumn-not-getting-fired-in-gatsby-production-build

**Comment by simonguo** [comment]
@sirrodgepodge  Upgrade `rsuite-table@3.14.5`

**Comment by sirrodgepodge** [comment]
it works!!!  Thank you @simonguo 

Go ahead and claim the bounty if you'd like

**Comment by simonguo** [comment]
@sirrodgepodge  Thank you very much for the problems you found and the bounty provided.
At the same time, you are also invited to use the [`rsuite`](https://rsuitejs.com/) component library, and you can contact us if you encounter any problems.
If rsuite can help you, I hope you can become our [sponsor](https://opencollective.com/rsuite).
