### ISSUE TITLE
classPrefix属性无效

### ISSUE THREAD

**Issue by Frank-MJ** [rsuite/rsuite-table#205]
| -------------- | ------- |
| `react`        | `^17.0.1` |
| `rsuite-table` | `^3.14.5` |

添加classPrefix属性后，没有穿透到所有div上，只是外层的div生效了

如下图所示：
![image](https://user-images.githubusercontent.com/16225885/111588432-86539680-87fe-11eb-9eec-bb4950690457.png)

**Comment by simonguo** [comment]
目前你可以通过设置 webpack 的环境变量进行全局替换前缀。

```js
new webpack.DefinePlugin({
    __RSUITE_CLASSNAME_PREFIX__: JSON.stringify('bre-')
})
```

**Comment by Frank-MJ** [comment]
> 目前你可以通过设置 webpack 的环境变量进行全局替换前缀。
> 
> ```js
> new webpack.DefinePlugin({
>     __RSUITE_CLASSNAME_PREFIX__: JSON.stringify('bre-')
> })
> ```
大佬，可以通过props属性classPrefix来达到这个效果嘛；组件现在是有这个属性的，只是没有穿透到内部；因为我们现在是基于你们这个rsuite-table组件进行二次封装的。添加webpack配置的话，所有小组用到这个组件都需要添加webpack配置，比较麻烦；
