### ISSUE TITLE
当Table组件设置固定高度和affixHeader属性的时候，底部有一段留白，怎么去掉呢

### ISSUE THREAD

**Issue by Frank-MJ** [rsuite/rsuite-table#209]
当Table组件 设置affixHeader和固定高度的时候，底部有一段留白，怎么去掉呢
使用包的版本信息：
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "rsuite-table": "^3.14.5",
![image](https://user-images.githubusercontent.com/16225885/112607750-779b5e00-8e54-11eb-9c91-ba51cde32fd9.png)

**Comment by simonguo** [comment]
这个问题已经修复过了 https://github.com/rsuite/rsuite-table/pull/184

你试一下安装以下版本看看能否解决你的问题
```
npm i rsuite@5.0.0-alpha.5
```
