### ISSUE TITLE
Styles are not the same as in the example

### ISSUE THREAD

**Issue by mpoteriecy** [rsuite/rsuite-table#220]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `17.0.2` |
| `rsuite-table` | `3.14.3` |

### What is the expected behavior?
The resize style is not the same between what I get in my app and what is on the documentation.
The resize should look like this:

https://user-images.githubusercontent.com/79851045/117639464-381a9e00-b184-11eb-9a59-7695470aad14.mov

### What is the current behavior?
And it looks like this:

https://user-images.githubusercontent.com/79851045/117639484-4072d900-b184-11eb-955a-9fea6213adb9.mov

### What are the steps to reproduce?
I am importing this style:
`import "rsuite-table/dist/css/rsuite-table.css";`

### Any additional comments? (optional)
I am having trouble to add sttles to get the exam set behavior and was wondering if I should export some extra style, or update anything to get this working :)

Thanks!

**Comment by simonguo** [comment]
The table style has been rewritten in rsuite. You can directly import the style of rsuite to achieve the same style.
```ts
import { Table }  from 'rsuite';
import 'rsuite/dist/styles/rsuite-default.css'
```
