### ISSUE TITLE
fixed column not working when map columns

### ISSUE THREAD

**Issue by zhoulijuanmiao** [rsuite/rsuite-table#233]
### Versions
"react": "^17.0.2",
"rsuite-table": "^3.15.1",

| package        | version |
| -------------- | ------- |
| `react`        | `X.Y.Z` |
| `rsuite-table` | `X.Y.Z` |

### What is the expected behavior?
fixed column working when map columns
### What is the current behavior?
fixed column not working when map columns

**Comment by simonguo** [comment]
Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).

**Comment by simonguo** [comment]
Upgrade to the latest rsuite-table and see if that solves your problem. This issue will be closed, if there are still problems, it can be reopened.

**Comment by JoeWrights** [comment]
遇到同样的问题，现在用的是最新版本的package

**Comment by simonguo** [comment]
@JoeWrights  能否通过 [codesandbox](https://codesandbox.io/s/5vq6zo2z5l) 复现一下你的问题

**Comment by JoeWrights** [comment]
> @JoeWrights 能否通过 [codesandbox](https://codesandbox.io/s/5vq6zo2z5l) 复现一下你的问题

可以的，我知道复现步骤了，在循环每个Column时外面包一层Fragment就会有这种问题

[复现例子](https://codesandbox.io/s/romantic-moon-48xwru?file=/src/index.js)
