### ISSUE TITLE
onScroll does not work as intended on mouse wheel scroll

### ISSUE THREAD

**Issue by vykintazo** [rsuite/rsuite-table#239]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `17` |
| `rsuite` | `5.0.0-beta.4` |
| `rsuite-table` | `5.0.0-alpha.8` |
- bug seems unrelated to rsuite version and can be replicated in all `rsuite-table` versions from `5.0.0-alpha.6`

### What is the expected behavior?
`onScroll` should always call latest reference to its callback, with up to date closure/scope.

### What is the current behavior?
Dragging scrollbar works as intended, but scrolling with a mouse wheel seems to call a reference of initially passed callback with outdated closure/scope.

### What are the steps to reproduce?
https://codesandbox.io/s/rsuite-table-scroll-bug-gt912
Try to scroll with wheel and scrollbar drag and see console output

### Any additional comments? (optional)
Looks like after Hook rewrite somewhere callback is memoized but not updated when it changes.

**Comment by raibikys** [comment]
Tested in my own project - same!
