### ISSUE TITLE
flattenData报错

### ISSUE THREAD

**Issue by jiandandkl** [rsuite/rsuite-table#241]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `16.14.0` |
| `rsuite-table` | `3.15.1` |

树状模式报`Cannot add property _parent, object is not extensible`的错
![image](https://user-images.githubusercontent.com/16009933/131772348-9cb0e997-ffab-4a8f-8ff2-7e2cd2fd3fcf.png)

改成这样就可以
![image](https://user-images.githubusercontent.com/16009933/131661046-3bd3f82d-05c2-41c5-9d1b-aca30ca44723.png)

把原flattenData方法复制到项目中使用却没问题

**Comment by simonguo** [comment]
能否通过 codesandbox 复现一下你的问题？

**Comment by jiandandkl** [comment]
> 能否通过 codesandbox 复现一下你的问题？

用codesandbox不能复现。。。
在这打了断点，执行完`item._parent = _parent;`,又会执行`getDerivedStateFromProps`,第二次执行才会报错
![image](https://user-images.githubusercontent.com/16009933/132208073-c6448735-ad65-4757-a557-49892ae98491.png)
![image](https://user-images.githubusercontent.com/16009933/132208441-ef772763-bfe3-4e5c-a840-841538c66223.png)
同时控制台出现`unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.`的warning

**Comment by simonguo** [comment]
你在你的环境试一下最新版本，看看是否存在同样的问题
```
npm i rsuite-table@next
```

**Comment by jiandandkl** [comment]
> 你在你的环境试一下最新版本，看看是否存在同样的问题
> 
> ```
> npm i rsuite-table@next
> ```

已升级，还是同样的错误

**Comment by simonguo** [comment]
@jiandandkl  通过 codesandbox 提供一下你完整的代码。

**Comment by jiandandkl** [comment]
> @jiandandkl 通过 codesandbox 提供一下你完整的代码。

sorry，公司项目，没法上传。。。

**Comment by Edymov** [comment]
I have the same issue too. But, using next.js. I can`t reproduce it via codesandbox
