### ISSUE TITLE
默认使用 rowKey 导致渲染错误

### ISSUE THREAD

**Issue by MarvelSQ** [rsuite/rsuite-table#255]
### Versions

| package        | version |
| -------------- | ------- |
| `rsuite-table` | `3.15.1` |

### What is the expected behavior?
react正常渲染
### What is the current behavior?
react渲染错误
### What are the steps to reproduce?
https://codesandbox.io/s/green-meadow-u9z17?file=/src/index.js

**Comment by simonguo** [comment]
@MarvelSQ  示例中的代码用的是 rsuite v5 我没发现什么渲染错误的问题，你的问题是出现在 rsuite@4.* 上的？
