### ISSUE TITLE
列渲染异常

### ISSUE THREAD

**Issue by lzfuchen** [rsuite/rsuite-table#256]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | 17.0.2 |
| `rsuite-table` | 5.0.1 |

### What is the expected behavior?
列可以正常渲染
### What is the current behavior?
横向左右快速滚动的时候，左侧的没有固定的列没有渲染出来
### What are the steps to reproduce?
快速左右拖动滚动条，最终滚动到最左侧，就会看到列没有渲染出来

https://codesandbox.io/s/vibrant-sara-wviuv

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/138246589-7062e73f-06ce-4c33-aefb-a723025984e7.png)
我这边看到的是渲染正常的，你能把渲染异常的效果截个图看一下吗？
