### ISSUE TITLE
使用ColumnGroup合并表头后，在Column中设置align未起作用

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite-table#276]
### Versions

| package        | version |
| -------------- | ------- | 
| `rsuite-table` | `5.2.0` | 

使用ColumnGroup合并表头后，在Column中设置align未起作用

![image](https://user-images.githubusercontent.com/18433241/143392081-6a6f282b-c7b4-48cb-97dd-00e7e5d69862.png)

**Comment by simonguo** [comment]
fixed in rsuite-table@5.2.2 and [rsuite@5.2.4](https://github.com/rsuite/rsuite/releases/tag/5.2.4)
