### ISSUE TITLE
使用ColumnGroup合并表头后，在Column中设置align设置left或right未起作用

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite-table#280]
### Versions

| package        | version |
| -------------- | ------- |
| `rsuite-table` | `5.2.1` |

### What is the expected behavior?
![image](https://user-images.githubusercontent.com/18433241/144371152-2abdad6e-3e48-4638-8fa1-9763f0193b13.png)

**Comment by simonguo** [comment]
fixed in rsuite-table@5.2.2 and [rsuite@5.2.4](https://github.com/rsuite/rsuite/releases/tag/5.2.4)
