### ISSUE TITLE
react版本错误？

### ISSUE THREAD

**Issue by zhurizhe** [rsuite/rsuite-table#3]
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

运行的时候出现的错误
https://facebook.github.io/react/warnings/refs-must-have-owner.html

**Comment by simonguo** [comment]
@zhurizhe  能看一下你的 `package.json` 文件吗？

**Comment by zhurizhe** [comment]
我看了，和你一样 "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-dom": "^15.4.2",

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite-table/blob/master/package.json
rsuite-table 现在用的 react 版本 0.14.*

**Comment by zhurizhe** [comment]
晕，那怎么办

**Comment by simonguo** [comment]
这个问题我们处理一下，好了通知你
