### ISSUE TITLE
设置列最小宽度不生效

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite-table#328]
### Versions

| package        | version |
| -------------- | ------- |
| `rsuite-table` | `5.3.6` |

表格列设置最小宽度无效，如下图官网示例:

![image](https://user-images.githubusercontent.com/18433241/160806151-96d74b13-12db-456e-b807-e0109bf3807e.png)

**Comment by simonguo** [comment]
重复的问题 https://github.com/rsuite/rsuite/issues/2426
