### ISSUE TITLE
rsuite-table 5.3.6 改变列宽度后触发

### ISSUE THREAD

**Issue by hedengxing** [rsuite/rsuite-table#333]
改变列宽度后触发 onResize 然后 columns 里的宽度有变 鼠标放上去有个蓝色竖线 竖线位置没错但是 表格宽度就是不会变
但是悬浮的 fixed: 'left' 改变是可以的 其他好像都是不可以
![1649228220(1)](https://user-images.githubusercontent.com/46393161/161914149-3c10b050-e4a8-48d2-bcf4-fb7847786ddb.jpg)

**Comment by simonguo** [comment]
> 改变列宽度后触发 onResize 然后 columns 里的宽度有变 鼠标放上去有个蓝色竖线 竖线位置没错但是 表格宽度就是不会变 但是悬浮的 fixed: 'left' 改变是可以的 其他好像都是不可以 ![1649228220(1)](https://user-images.githubusercontent.com/46393161/161914149-3c10b050-e4a8-48d2-bcf4-fb7847786ddb.jpg)

请把你遇到的问题组织好语言后，再重新说一次。 如果你觉得自己还是不能描述清楚，请通过 https://codesandbox.io/ 把你遇到的问题复现出来。

**Comment by hedengxing** [comment]
我改变表格宽度 触发组件回调 onResize
columns 数据改变 但界面上表格并没有改变

**Comment by hedengxing** [comment]
哦哦 我知道问题了

**Comment by hedengxing** [comment]
可以了
