### ISSUE TITLE
Create new rs table inside the expanded row

### ISSUE THREAD

**Issue by bzhouFubo** [rsuite/rsuite-table#342]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `17.0.38` |
| `rsuite` | `5.9.0` |

### What is the expected behavior?
There should a table displayed within the expanded row

### What is the current behavior?
The table header and cell are misaligned.  And I notice all the class names have an extra "table" in the name, e.g. "rs-table-table-cell-group" and "rs-table-table-cell-group-scroll"

### What are the steps to reproduce?
Just try insert any rs table inside the expanded row.

**Comment by simonguo** [comment]
Check that your dependencies have both rsuite and rsuite-table installed. If so, remove rsuite-table, and rsuite will automatically install the correct version that depends on rsuite-table.

If the above does not solve the problem, try to upgrade rsuite to the latest version.

**Comment by bzhouFubo** [comment]
Hi Simon, thanks for the help. I tried both ways that you suggested but still seeing the issue.  I've upgrade to version below

"rsuite": "^5.15.1"
