### ISSUE TITLE
当页面中存在2个reuite-table时，第二个table的className会从rs-table变成rs-table-table，导致样式无效

### ISSUE THREAD

**Issue by YiStick** [rsuite/rsuite-table#345]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `X.Y.Z` |
| `rsuite-table` | `5.5.5` |

在同一个页面使用2个rsuite-table。一个table在基本页面中，另一个table以antd弹框的形势出现在其中。弹框中的table的className 会从rs-table变成rs-table-table 这种形式 就造成了样式错乱。然后本身的rsuite-table的样式就不会生效。我目前的解决方案是以父容器包裹，从写样式的方式解决的。

**Comment by simonguo** [comment]
https://rsuitejs.com/components/table/
这个页面存在多个 Table，未发现你所说的样式问题。

你的结构上是表格嵌套一个表格吗？

**Comment by YiStick** [comment]
是表格中点击按钮 显示一个模态框，模态框里面展示了一个表格。然后class-name就发生了变化。



在 2022-06-21 14:23:54，"Simon Guo" ***@***.***> 写道：

https://rsuitejs.com/components/table/
这个页面存在多个 Table，未发现你所说的样式问题。

你的结构上是表格嵌套一个表格吗？

**Comment by YiStick** [comment]
是表格中的操作按钮，点击后出现一个模态框，模态框里面有一个表格。模态框里面的表格class-name就发生了我描述的那样的变化。

**Comment by simonguo** [comment]
@YiStick  我猜你是把 Model 定义在 Table 内部了，导致 Table 内部拿到 context 被覆盖。context 内部定义了 classPrefix ，所以才出现 className 前缀出现问题。

要解决这个问题，你可以通过把 Modal 定义在 Table 外部 (我们也推荐你这样做，否则在 Table 渲染过程中会创建多个 Modal)，渲染一个 Modal 。

后续我们会修复该问题。

**Comment by YiStick** [comment]
@simonguo  是的 我就是直接把 Table 定义在了 Modal 内部的。感谢回复。我尝试您的方法来解决这个问题。
