### ISSUE TITLE
Aways showing loading component when using renderLoading

### ISSUE THREAD

**Issue by morrissey-br** [rsuite/rsuite-table#368]
### Versions

| package        | version |
| -------------- | ------- |
| `react`          | `18.2.0` |
| `rsuite-table` | `5.19.0` |

### What is the expected behavior?
When using a custom component as loader in renderLoading prop, the berravior has to be the same as not passing any custom loader.

### What is the current behavior?
When passing a function that return a custom componente to be used as loading component, its show the custom loading component, no matter the loading prop is true or false.

### What are the steps to reproduce?

1. Create a table;
2. Put loading state to false;
3. Create a function that return a custom component in the renderLoading prop;

Exemple: https://codesandbox.io/s/serene-wave-qgg8m9

### Any additional comments? (optional)

This may be caused by the prop loadAnimation that is user in the checking condition to show the loading component. This not occur in the default loading component because it uses css class to hide the component when loading is false.
The solution may be remove the loadAnimation prop at all, because isn't used in anything except to this condition.
This may cause error in the rsuite repository, but I believe this is needed.
Another solution, if you have any plans to use loadAnimation prop in the future is to remove the default true declaration in the export of this component in the rsuite repository.

**Comment by simonguo** [comment]
fixed in https://github.com/rsuite/rsuite-table/pull/370

https://rsuite.github.io/rsuite-table/#15
