### ISSUE TITLE
Can't sort table when isTree is enabled

### ISSUE THREAD

**Issue by hedzerkoolstra** [rsuite/rsuite-table#375]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `17.0.1` |
| `rsuite` | `5.18.0` |

### What is the expected behavior?
I want to sort my table when isTree is set to true.

### What is the current behavior?
When I try to sort a column the sorted data is injected into the table but my screen is not updating.

### What are the steps to reproduce?
Create a table with nested rows and enable isTree. 
Enable sortable for any of the columns
Click on the sort icon
Nothing happens

See: https://codesandbox.io/s/weathered-platform-cb3b8j?file=/index.js

### Any additional comments? (optional)

I did some debugging into Table.tsx which might be helpful.
I see that whenever isTree is true, [filterTreeData() is used](https://github.com/rsuite/rsuite-table/blob/54868f769b25c75a02f59f07dd4e521524cdfeaa/src/Table.tsx#L518) to mutate `dataProp`.
However, when I set a breakpoint in `filterTreeData` it only hits it on the initial load of the table, not when clicking the sort icon.
Shouldn't this function need to trigger again whenever `dataProp` is updated (eg. when new, sorted data is injected)?
Hope this helps, thanks for looking into it!

**Comment by simonguo** [comment]
hi @hedzerkoolstra You should update the data after triggering the sort click, and the data should be immutable.

The following is a reference example
https://codesandbox.io/s/long-haze-4fz9bk

**Comment by hedzerkoolstra** [comment]
Hi @simonguo, that fixed the issue, thanks you very much!
