### ISSUE TITLE
warn：Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by ghyghoo8** [rsuite/rsuite-table#383]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `17.0.0` |
| `rsuite-table` | `5.8.0` |

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/363129/202139283-388a2ac4-fa58-4bc3-a3df-113d1581be5a.png)

👇🏻下面是初始化的code
![image](https://user-images.githubusercontent.com/363129/202139576-30c66fc9-017e-4ab7-b812-c158036c245d.png)

**Comment by simonguo** [comment]
Hi, please reproduce your problem completely through [codesandbox](https://codesandbox.io/) !
