### ISSUE TITLE
Hovering on table header, the background color is changed

### ISSUE THREAD

**Issue by Enivia** [rsuite/rsuite-table#384]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `18.2.0` |
| `rsuite-table` | `5.8.0` |

### What is the expected behavior?
Hovering on table header, the background color is changed

### What is the current behavior?
The head color is unchanged

### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/23496031/202344130-4198ff1a-fc6c-4535-9a17-488e043dc827.png)

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite-table/pull/386
