### ISSUE TITLE
Scrollbar doesn't display on resize after updating to React 18

### ISSUE THREAD

**Issue by hedzerkoolstra** [rsuite/rsuite-table#398]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `18.2.0` |
| `rsuite-table` | `5.27.0` |

### What is the expected behavior?
When I resize a column and create a grid larger then the wrapper a horizontal scrollbar should become visible.

### What is the current behavior?
The scroll bar now doesn't appear right away. Only on a second action (another resize, a sort) the scrollbar will appear.

### What are the steps to reproduce?
You can try resizing in this codesandbox example:
https://codesandbox.io/s/keen-hodgkin-0gmpf6?file=/index.js

It's a fork of your own resize example in the docs. In the original example there is no problem. But I updated the example to React 18 and now the issue is appearing. Thanks for looking into it!

**Comment by simonguo** [comment]
Fixed in [rsuite-table@5.9.0](https://github.com/rsuite/rsuite-table/releases/tag/5.9.0)
