### ISSUE TITLE
改变列宽时，横向滚动条位置回到最左侧

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite-table#4]
Table 调整列宽时，横向滚动条回到最左侧
![image](http://7xpn4q.com1.z0.glb.clouddn.com/QQ20170710-104818.gif)

**Comment by simonguo** [comment]
Fix: https://github.com/rsuite/rsuite-table/commit/1013d5bed2150f7af86f8d81fc2ca25b2c1b42c5
