### ISSUE TITLE
为什么和antd的风格这么像？

### ISSUE THREAD

**Issue by qazzhoubin** [rsuite/rsuite-table#41]
为什么和antd的风格这么像？

**Comment by simonguo** [comment]
@qazzhoubin ，Table 的设计原型：

- https://rsuitejs.com/design/index.html#artboard59
- https://rsuitejs.com/design/index.html#artboard60
- https://rsuitejs.com/design/index.html#artboard61
- https://rsuitejs.com/design/index.html#artboard62
- https://rsuitejs.com/design/index.html#artboard63
- https://rsuitejs.com/design/index.html#artboard64
- https://rsuitejs.com/design/index.html#artboard65
- https://rsuitejs.com/design/index.html#artboard66

你需要解决的问题是？
