### ISSUE TITLE
table树表格超过三级节点缩进失效

### ISSUE THREAD

**Issue by surongm** [rsuite/rsuite-table#416]
### Versions
https://table.rsuitejs.com/#tree
    "rsuite-table": "^5.10.2",

`const data = mockTreeData({
  limits: [2, 3, 3],
  labels: layer => {
    if (layer === 0) {
      return faker.vehicle.manufacturer();
    } else if (layer === 1) {
      return faker.vehicle.fuel();
    }
    return faker.vehicle.vehicle();
  },
  getRowData: () => ({
    price: faker.commerce.price(10000, 1000000, 0, '$', true),
    rating: faker.finance.amount(2, 5)
  })
});

const App = () => {
  const [tree, setTree] = React.useState(true);
  return (
    <div>
      <label>
        <input
          type="checkbox"
          checked={tree}
          onChange={() => {
            setTree(!tree);
          }}
        />
        isTree
      </label>
      <Table
        virtualized
        isTree={tree}
        defaultExpandAllRows
        bordered
        cellBordered
        rowKey="value"
        height={400}
        data={data}
        /** shouldUpdateScroll: whether to update the scroll bar after data update **/
        shouldUpdateScroll={false}
        onExpandChange={(isOpen, rowData) => {
          console.log(isOpen, rowData);
        }}
        renderTreeToggle={(icon, rowData) => {
          if (rowData.children && rowData.children.length === 0) {
            return <SpinnerIcon spin />;
          }
          return icon;
        }}
        onRowClick={rowData => {
          console.log(rowData);
        }}
      >
        <Column flexGrow={1}>
          <HeaderCell>Vehicle 🚗</HeaderCell>
          <Cell dataKey="label" />
        </Column>
        <Column width={180}>
          <HeaderCell>Rating ⭐️</HeaderCell>
          <Cell>
            {rowData =>
              Array.from({ length: rowData.rating }).map((_, i) => <span key={i}>⭐️</span>)
            }
          </Cell>
        </Column>
        <Column width={100}>
          <HeaderCell>Price 💰</HeaderCell>
          <Cell dataKey="price" />
        </Column>
      </Table>
    </div>
  );
};

ReactDOM.render(<App />);`
![image](https://user-images.githubusercontent.com/41141486/229402197-62692816-4c49-42a0-9a46-f125cee55018.png)

树表格三级的子节点层级没有缩进，树结构不明显。

之前使用是好的，是不是最近升版了还是其他原因

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite-table/pull/413 这个PR 导致的新问题，你先使用上一个版本 5.10.1

**Comment by Edymov** [comment]
> #413 这个PR 导致的新问题，你先使用上一个版本 5.10.1

I don`t think this can somehow affects tree offests. This PR is only for for fixing adding parentId to rowData and does not change tree rendering logic

**Comment by simonguo** [comment]
@surongm  Fixed in `rsuite-table@5.10.3`

@Edymov  Because the parent node of the parent node cannot be obtained. However, I have rewritten flattenData, you can use the latest version of `rsuite-table` to check whether the problems you encountered before still exist.

**Comment by surongm** [comment]
rsuite-table@5.10.3 已经可以了 非常感谢！
请问单使用rsuite  有修改这个问题做升级吗

**Comment by simonguo** [comment]
> rsuite-table@5.10.3 已经可以了 非常感谢！
> 请问单使用rsuite 有修改这个问题做升级吗

rsuite 每周四/五会升级
