### ISSUE TITLE
当expand和verticalAlign 同时使用时cell的height随着row变化

### ISSUE THREAD

**Issue by JammyLin** [rsuite/rsuite-table#423]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `18.2.0` |
| `rsuite` | `5.31.0` |

### What is the expected behavior?
当cell初始化以后height不再变化。
### What is the current behavior?
当cell的expand展开后cell的height变高了，content下移了。
### What are the steps to reproduce?
https://codesandbox.io/s/blue-mountain-ewqxol?file=/index.js 这是简单的例子。

**Comment by simonguo** [comment]
Fixed in [rsuite-table@5.10.5](https://github.com/rsuite/rsuite-table/releases/tag/5.10.5)
