### ISSUE TITLE
scroll with arrow keys

### ISSUE THREAD

**Issue by farshidinanloo** [rsuite/rsuite-table#428]
### What problem does this feature solve?

in tables with big height when we want to scroll horizontally we should first scroll down to bottom of the table to grab scroll bar and then scroll horizontally it would be better if we can scroll horizontally with arrow keys in keyboard

**Comment by simonguo** [comment]
Supported in [v5.13.0](https://github.com/rsuite/rsuite-table/releases/tag/5.13.0)
