### ISSUE TITLE
flexGrow在性能不太好时，能看到初始宽度不对

### ISSUE THREAD

**Issue by fallenleavesguy** [rsuite/rsuite-table#430]
bug提到rsuite去了

https://github.com/rsuite/rsuite/issues/3176

**Comment by simonguo** [comment]
Fixed in [rsuite-table@5.10.5](https://github.com/rsuite/rsuite-table/releases/tag/5.10.5)

**Comment by fallenleavesguy** [comment]
@simonguo 

rsuite更新了吗

**Comment by simonguo** [comment]
rsuite 会在每周五更新，你可以关注社区通知

![EF9BA404-98DC-4CDE-94B8-BBCF1E6390DB](https://github.com/rsuite/rsuite-table/assets/1203827/ce24bccc-b610-43e0-a106-3d37837f9357)
