### ISSUE TITLE
Table树表格开启虚拟化后，收起节点后导致表格的transformY计算错误

### ISSUE THREAD

**Issue by 276340452** [rsuite/rsuite-table#438]
| package        | version |
| -------------- | ------- |
| `react`        | `18.2.0` |
| `rsuite-table` | `5.29.Z` |

滚动到最后收起最后一条数据

https://codesandbox.io/s/happy-maxwell-4v1qij?file=/src/App.js

最后发现是 useTableDimension 中 data 传入数据是 dataProp 导致计算出错

``` ts
useTableDimension({
    // data: dataProp,
    data: data, // 将 dataProp 修改为 data 后就解决了
    width: widthProp,
```

**Comment by huihui925** [comment]
同样的问题 怎么解决？

**Comment by 276340452** [comment]
> 同样的问题 怎么解决？
修改 这个文件/node_modules/rsuite-table/es/Table.js
大概在 205 行左右
var _useTableDimension = useTableDimension({
-    data: dataProp,
+    data: data,

**Comment by simonguo** [comment]
@276340452  @huihui925  在这个 PR https://github.com/rsuite/rsuite-table/pull/462 中已修复。

修复后的示例 https://codesandbox.io/s/magical-johnson-85rvwd
