### ISSUE TITLE
虚拟滚动的时候怎么能让他出现白屏。

### ISSUE THREAD

**Issue by duxiaoran** [rsuite/rsuite-table#439]
我的table 特别复杂，有50列，还有各种自定义，我现在希望滚动的时候有白屏，如果没有白屏滚动的时候页面一卡一卡的，体验不太好，我是希望他正常滚，出现白屏也没事。我该怎么处理做呢？有提供属性吗？

**Comment by simonguo** [comment]
你这种情况和这个问题类似 https://github.com/rsuite/rsuite-table/issues/436 ，暂时没提供好的方式处理。希望你先从业务设计上进行优化，减少列和单元格的复杂度。
