### ISSUE TITLE
虚拟化树表格折叠bug，table白屏 滚动条重置顶部

### ISSUE THREAD

**Issue by huihui925** [rsuite/rsuite-table#443]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `16.8.6` |
| `rsuite-table` | `^5.10.6` |

### 复现步骤?

虚拟化树table默认展开全部节点，节点层级嵌套深，table数据多有纵向滚动条，将table滚动到最底部，点击最后一个节点 收起节点按钮，表格body区域白屏，且滚动条会自动重置到顶部。

案例1地址：[https://codesandbox.io/s/sweet-tristan-wmt3ts](https://codesandbox.io/s/sweet-tristan-wmt3ts)
案例2地址：[https://codesandbox.io/s/happy-maxwell-4v1qij?file=/src/App.js](https://codesandbox.io/s/happy-maxwell-4v1qij?file=/src/App.js)

**Comment by huihui925** [comment]
@simonguo

**Comment by huihui925** [comment]
#438 同样的问题

**Comment by 276340452** [comment]
还有另一个问题会导致空白
```
/node_modules/rsuite-table/es/utils/useScrollListener.js
// 大概在324行左右
    var _getControlledScrollT = getControlledScrollTopValue(top),
        nextScrollY = _getControlledScrollT[0],
        handleScrollY = _getControlledScrollT[1];

    -    var height = getTableHeight();
    +    var height = getTableHeight() - headerHeight;
```
上面的 height 高度计算错误
