### ISSUE TITLE
Cannot set 'resizable' and 'flexGrow' together in <Column> in latest version

### ISSUE THREAD

**Issue by JoeWrights** [rsuite/rsuite-table#445]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `X.Y.Z` |
| `rsuite-table` | `X.Y.Z` |

**Comment by JoeWrights** [comment]
@simonguo 我看5.11.0的release里有这个新feature，但是实际使用是无效的，[例子](https://codesandbox.io/s/dazzling-colden-p427ue?file=/src/index.js)

**Comment by MarvelSQ** [comment]
@JoeWrights table在children更新时，会重置宽度缓存，导致重新进入 flexWidth 计算

**Comment by JoeWrights** [comment]
> @JoeWrights table在children更新时，会重置宽度缓存，导致重新进入 flexWidth 计算

那这里怎么处理呢

**Comment by MarvelSQ** [comment]
结合场景来看，width应该可以改成受控的

**Comment by JoeWrights** [comment]
> 结合场景来看，width应该可以改成受控的

我那个例子不就是吗，大佬，所以我没明白那个feature解决了什么问题😹

**Comment by MarvelSQ** [comment]
之前的feature没有考虑到受控和数据刷新，仅是让resizable可以填充剩余空间。

测试用例也没有覆盖受控刷新

**Comment by MarvelSQ** [comment]
@JoeWrights 看一下 #447 这个PR是否可以解决你的问题

**Comment by JoeWrights** [comment]
> @JoeWrights 看一下 #447 这个PR是否可以解决你的问题

可以的

**Comment by JoeWrights** [comment]
@MarvelSQ 
![img_v2_7f192ad1-b184-4673-a8a9-7a9ca00a60dg](https://github.com/rsuite/rsuite-table/assets/38278949/b29f36c2-e767-471a-8cb5-ace70d5f9867)
还有个问题，当column的宽度之和小于整个table的宽度，会出现最右边空白的情况，如果没有column设置flexGrow，是不是应该自动对column进行比例等分撑满整个table

**Comment by MarvelSQ** [comment]
> @MarvelSQ ![img_v2_7f192ad1-b184-4673-a8a9-7a9ca00a60dg](https://user-images.githubusercontent.com/38278949/255518695-b29f36c2-e767-471a-8cb5-ace70d5f9867.jpg) 还有个问题，当column的宽度之和小于整个table的宽度，会出现最右边空白的情况，如果没有column设置flexGrow，是不是应该自动对column进行比例等分撑满整个table

嗯，确实有这种需求，算是新的feature，可以在新PR里解决。

同时还要考虑如何禁止定宽列扩张的情况
