### ISSUE TITLE
table 设置的height大于内容高度，表格横向滚动到最右边出现截断

### ISSUE THREAD

**Issue by JoeWrights** [rsuite/rsuite-table#451]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `X.Y.Z` |
| `rsuite-table` | `X.Y.Z` |

### Any additional comments? (optional)

[例子](https://codesandbox.io/s/dazzling-colden-p427ue?file=/src/index.js)

**Comment by simonguo** [comment]
修复后的示例: https://codesandbox.io/s/inspiring-gianmarco-2635qy
