### ISSUE TITLE
The first + sign of the tree data seems to be unable to open, and there is no problem in the back.

### ISSUE THREAD

**Issue by staralloff** [rsuite/rsuite-table#46]
用你的例子做了个树形数据的table，第一个“+”点不开，后面的都可以。

**Comment by simonguo** [comment]
你是单独使用 rsuite-table, 还是在 rsuite 中使用？

示例地址:
rsuite: https://rsuitejs.com/components/table
rsuite-table: https://rsuite.github.io/rsuite-table/

如果示例没有解决你的问题，你可以把你的代码写在 https://codesandbox.io ，我看一下。

**Comment by staralloff** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import { Table, Column, HeaderCell, Cell } from '../components/table/index';
import '../components/table/less/index.less';

const EditCell = ({ rowData, dataKey, onChange, ...props }) => {
  return (
    <Cell {...props}>
        {rowData.status === 'ENABLED' ? (
            <input
                className="input"
                defaultValue={rowData[dataKey]}
                onChange={(event) => {
                    onChange && onChange(rowData.id, dataKey, event.target.value);
                }}
            />
        ) : rowData[dataKey]}
    </Cell>
  );
};

const data = [
  {
    labelName: 'Person',
    status: 'ENABLED',
    count: 666
  },
  {
    labelName: 'Car',
    status: 'ENABLED',
    children: [
      {
        key: '1-1',
        labelName: 'Benz',
        status: 'ENABLED',
        count: 460
      },
      {
        key: '1-2',
        labelName: 'BMW',
        status: 'ENABLED',
        children: [
          {
            key: '1-2-1',
            labelName: '2Serial',
            status: 'ENABLED',
            count: 103,
            email: '123@ss.com',
            id: 1,
            children: [
              {
                key: '1-2-1-1',
                labelName: 'Sports',
                status: 'DISABLED',
                count: 502
              },
              {
                key: '1-2-1-2',
                labelName: 'RaceCar',
                status: 'ENABLED',
                count: 502
              },
              {
                key: '1-2-1-3',
                labelName: 'Convertible',
                status: 'DISABLED'
              },
              {
                key: '1-2-1-4',
                labelName: 'SUV',
                status: 'DISABLED'
              },
              {
                key: '1-2-1-5',
                labelName: 'TripCar',
                status: 'DISABLED',
                count: 34
              }
            ]
          },
          {
            key: '1-2-2',
            labelName: 'Target Customer',
            status: 'ENABLED',
            count: 364,
            children: [
              {
                key: '1-2-2-1',
                labelName: 'Financial Plan',
                status: 'DISABLED'
              },
              {
                key: '1-2-2-2',
                labelName: 'Appointment test Drive',
                status: 'ENABLED'
              }
            ]
          }
        ]
      }
    ]
  },
  {
    key: '2',
    labelName: 'Game',
    status: 'ENABLED',
    count: 834,
    children: [
      {
        key: '2-1',
        labelName: 'NetworkGame',
        status: 'DISABLED'
      },
      {
        key: '2-2',
        labelName: 'MobileGame',
        status: 'ENABLED'
      }
    ]
  },
  {
    key: '3',
    labelName: 'Media',
    status: 'ENABLED',
    count: 534,
    children: [
      {
        key: '3-1',
        labelName: 'Phone',
        status: 'ENABLED',
        children: []
      },
      {
        key: '3-2',
        labelName: 'Computor',
        status: 'DISABLED'
      },
      {
        key: '3-3',
        labelName: 'Watch',
        status: 'ENABLED'
      }
    ]
  }
];


export default class TablePage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: data.filter((item, index) => index < 20)
    };
    this.handleChange = this.handleChange.bind(this);
  }
  handleChange(id, key, value) {
    const { data } = this.state;
    const nextData = clone(data);
    nextData.find(item => item.id === id)[key] = value;
    this.setState({
      data: nextData
    });
  }

  render() {
    const { data } = this.state;
    return (
      <div>
        <Table autoHeight isTree defaultExpandAllRows minHeight={260} height={400} data={data}
          onExpandChange={(isOpen, rowData) => {
            console.log(isOpen, rowData);
          }}
          renderTreeToggle={(icon, rowData) => {
            if (rowData.labelName === 'Phone') {
              return <i className="icon icon-spin icon-spinner" />;
            }
            return icon;
          }}
        >
          <Column flexGrow={1}>
            <HeaderCell>Label</HeaderCell>
            <Cell dataKey="labelName" />
          </Column>

          <Column width={100}>
            <HeaderCell>Status</HeaderCell>
            <Cell dataKey="status" />
          </Column>

          <Column width={100}>
            <HeaderCell>Count</HeaderCell>
            <Cell dataKey="count" />
          </Column>

          <Column width={200}>
            <HeaderCell>Email</HeaderCell>
            <EditCell dataKey="email" onChange={this.handleChange} />
          </Column>

        </Table>
      </div>
    );
  }
}


我就是这么写的   因为公司保密严格，只能用公司的私有npm库，库里没有rsuite的lib，所以我就照样写了一个拿来用了。不是很懂前端，不知道是不是Cell里那个renderExpandIcon那个方法的问题

**Comment by hiyangguo** [comment]
@sachieyuan 首先，希望能阅读我们的 [新手指南](https://rsuitejs.com/guide/usage) ，并按照说明一步一步进行操作。然后麻烦将业务相关的代码删掉，将代码逻辑抽出来并将示例贴到  https://codesandbox.io  中，方便我们 Debug 。

**Comment by staralloff** [comment]
我好像知道原因了，你们展开是靠那个rowkey控制的，我数据里第一条数据没有key的值所以点不了，不好意思啊
