### ISSUE TITLE
Getter for current scroll position.

### ISSUE THREAD

**Issue by chrisantreasian-hdai** [rsuite/rsuite-table#471]
### What problem does this feature solve?

Accessing current scroll position outside of the scope of the onScroll callback. The reason I am making this proposition is that we are debouncing the onScroll event to prevent over aggressive function/api requests for an infinite scroll behavior. However the debounce is inhibiting the event from firing when we reach the bottom of the scrollable container. Ideally we will have away to access the current scroll positions by using a getter method in order to check after the scroll debounce completes.

### What does the proposed API look like?
```
const SomeComponent = (props: any) => {
  const getScrollPosition = () => (position: {x: number, y: number}) => position;
  const scrollCallback = () => {
     ...
  }
  const someOtherMethod = () => {
     const position = getScrollPositon();
     // do anything with position.x or position.y
  }
  return <Table
      onScroll={scrollCallback}
      getScrollPosition={getScrollPosition}
   />
}
```
Alternatively and possible even more ideally it would be a member of the table ref.

**Comment by simonguo** [comment]
Supported in https://github.com/rsuite/rsuite-table/pull/473
