### ISSUE TITLE
Drag and drop issue in table 

### ISSUE THREAD

**Issue by ravi906770** [rsuite/rsuite-table#487]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | ^18.2.0 |
| `rsuite-table` | 5.18.2 |

### What is the expected behavior?
when i slightly drag on the first row of the table , it should stay as it is.

### What is the current behavior?
when i slightly drag on the first row of the table , it will directly drop on the second last row of the table

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite-table/pull/491

**Comment by ravi906770** [comment]
Thank you @simonguo and Digvijay Sinh Chauhan !
