### ISSUE TITLE
Better indentation for table tree rows

### ISSUE THREAD

**Issue by AdrienFromToulouse** [rsuite/rsuite-table#506]
### What problem does this feature solve?

Currently when using the tree table with mixed row (one with children, one without), there would be an alignment issue:

<img width="1107" alt="Screenshot 2024-10-14 at 12 22 16" src="https://github.com/user-attachments/assets/1b3386d0-0f7c-46bb-b9c7-204ee773fc52">

On the screenshot above, `Toyota` and `Lamborghini` look like being children from  `New 1`.

What would be ideal would be to align the Toyota with the `New 1`:

<img width="188" alt="Screenshot 2024-10-14 at 12 24 51" src="https://github.com/user-attachments/assets/6693ac9d-d667-4c66-8c40-e10326038f9e">

This is achievable with the prop `renderRow` but it creates some edge case where the hover would be then too much on the left etc... 

Would it be possible to have it changed natively in the `Table` component?

Cheers,

**Comment by simonguo** [comment]
You don't need to use `renderRow`, you can solve it by customizing the style of the cell.



```tsx
<Cell dataKey="label" />
```

 Change to:

```tsx
<Cell>
  {(rowData) => {
    const paddingLeft = rowData.children?.length ? 0 : 26;
    return <span style={{ paddingLeft }}>{rowData.label}</span>;
  }}
</Cell>
```
