### ISSUE TITLE
`Table-cell-content` Vertical alignment issue.

### ISSUE THREAD

**Issue by sarojregmi200** [rsuite/rsuite-table#507]
### Versions

| package        | version |
| -------------- | ------- |
| `react`        | `^18.3.1` |
| `rsuite-table` | `^5.19.1` |

### What is the expected behavior?
The row data should be vertically center aligned.

### What is the current behavior?
It is slightly off above the center position as shown in the snapshot below.
![20241015_22h51m00s_grim](https://github.com/user-attachments/assets/8ca85f7c-8b21-4c37-8bf7-4425c133bbc5)

### What are the steps to reproduce?
Just use the first example provided in the official documentation. 
[Example link:](https://rsuitejs.com/components/table/#basic)

> Further details, Docs has it perfectly centered and the local implementation that i did has it slightly off center. It is most probably because of the font family being used. I have not used the same font family as in the example.
> So, due to those fonts having different height it is not aligned in the center in both cases.

I have solved the issue, explicitly justifying contents to the center of the row in my implementation here.
Solution that worked for me: [solution](https://github.com/sarojregmi200/bright-table/commit/096830dec192d4d179e062aafa2db5bf87d36d4b#diff-8f65823028d9e4c1d91bc76658b74ec244e6f71ee544854a98f1eaaa8228112fR104)

**Comment by simonguo** [comment]
You can achieve the vertical centering effect by using the `verticalAlign` property of `Column`, as shown below:
```tsx
<Column  verticalAlign="middle">
  ...
</Column>
```

**Comment by sarojregmi200** [comment]
Thanks. 
I see so, slightly offcenter is intended default way?
