### ISSUE TITLE
ios9.3及以下版本系统有bug

### ISSUE THREAD

**Issue by yingxiaoqiang** [rsuite/rsuite-table#57]
ios9.3及以下版本系统里面，toggleClass.js文件line22，当node为空数组的时候没有length属性，会直接调用line28的toggleClass方法，会导致dom-lib/lib/classNames/removeClass.js中13行的target.className报undefined

![image](https://user-images.githubusercontent.com/16712872/51728880-bd114480-20ac-11e9-8e91-446672a7c9ef.png)

![image](https://user-images.githubusercontent.com/16712872/51728888-cef2e780-20ac-11e9-933c-d78d6d6acdc4.png)

**Comment by Pixel-Daze** [comment]
遇到了一样的问题

**Comment by simonguo** [comment]
请升级到最新的 `rsuite-table@latest`,  另外不推荐在移动设备上使用表格。
