### ISSUE TITLE
Cell 中内容过长时被截断的问题有解么？

### ISSUE THREAD

**Issue by dongsuo** [rsuite/rsuite-table#60]
Cell 中内容过长时因为用了`text-overflow: ellipsis;`导致内容被截断，请问有没有考虑过用换行的形式来展示么？换行的话会导致表格内容高度计算出错么？这个问题在无限滚动这种情况下是不是无解呢？

**Comment by simonguo** [comment]
1.支持自动换行， `<Table  wordWrap >`
2.不会导致高度计算出错
3.长列表无限滚动，暂时不兼容 wordWrap， 但是有解。

**Comment by zxyling** [comment]
虚拟table开启换行之后，虚拟渲染被被自动关掉，这个有什么解决方案么
