### ISSUE TITLE
什么时候可以加入行和列都可以拖拽的功能？

### ISSUE THREAD

**Issue by jasonLeeeeee** [rsuite/rsuite-table#63]

**Comment by simonguo** [comment]
会在 react 4.0 版本发布前开发好这个这个功能。预估在第二季度，暂时还没办法给你准确的时间点，抱歉。

**Comment by GendSmith** [comment]
期待！

**Comment by simonguo** [comment]
@GendSmith @jasonLeeeeee  通过 rsuite-table 与 react-dnd 组合，实现的可拖拽列和行的参考：
https://github.com/rsuite/rsuite-table/blob/master/docs/md/DraggableTable.md

预览（最后一个示例）:
http://rsuite.github.io/rsuite-table/
