### ISSUE TITLE
可以考虑完善一下排序功能

### ISSUE THREAD

**Issue by GendSmith** [rsuite/rsuite-table#65]
目前的排序的sortColumn只支持一个，可以考虑支持多个，举例一个场景就是：先按照出生日期排好序，然后按照英文名字典序在原来的基础上继续排序。

**Comment by simonguo** [comment]
@GendSmith  多级排序在 UI 和交互设计上没有一个好的通用方式，如果设计不好反而会给使用者带来困惑，你如果有好的设计方式（或者在哪里看到过）可以分享一下。

另外，你目前的使用场景完全可以在数据获取上把第二级的排序设置为默认排序，不需要用户操作。

**Comment by GendSmith** [comment]
我在dataGrip上就常用多级排序，我觉得你们的交互就很不错了，箭头的上下表示排序方向，多个箭头不同方向其实应该也比较好理解

**Comment by GendSmith** [comment]
![image](https://user-images.githubusercontent.com/22338894/53789678-f6688a00-3f5f-11e9-8330-d1d45e3f2c00.png)
文档在窄屏上似乎需要设置好侧边栏的z-index?

**Comment by simonguo** [comment]
感谢，文档的问题我们修复一下，如果你有兴趣的也可以给我们提 PR。

dataGrip 上面的交互，排队点击的时候，是怎么区分第一次点击和第二次点击的？

**Comment by GendSmith** [comment]
dataGrip我也不知道怎么区分的，不过我猜应该可以设置sortColumn为一个数组，因为现在sortColumn是string，如果设置成数组的话，sortColumn.push(newSortColumn)，开发者根据onSortColumn函数返回的sortColumn数组应该就可以设置自己的排序规则了

**Comment by simonguo** [comment]
@GendSmith  组件 API 设计很简单，这个改动不难，我说的是在UI交互上怎么区分。

**Comment by GendSmith** [comment]
由浅到深的颜色？最深表示排序规则是最新的

**Comment by simonguo** [comment]
切换排序字段，取消排序字段呢？

**Comment by GendSmith** [comment]
调整颜色

**Comment by simonguo** [comment]
比如表格表头有这几列：
 | id | name |  email  |  age  | 


- 首先，点击一下 id  , 这个时候排序按照 id 顺序排序
- 然后，点击一下 age，这个时候一级排序是 id , 二级排序是 age

页面上的显示效果是， id 旁边的箭头的颜色浅一些，age 旁边的箭头颜色深一些。

现在问题来了
1.问题1：我想把 id 按照倒序排列，这个时候点击一下 id 列， 这个时候 id 到底算一级排序还是算 二级排序？
2.问题2： 在上面那个状态下，我要怎么点击页面交互，才能实现切换到一级排序 name 按照顺序，二级排序 email 顺序？

**Comment by GendSmith** [comment]
问题1我的想法是：以最新的点击作为最高级的排序（颜色最深）
问题2:在上面的状态，多点几次id和age，取消对他们的排序，接下来就重新排序

**Comment by simonguo** [comment]
- 问题1，如果在颜色设计合理的情况下，适应一段时间，还算逻辑上通顺。
- 问题2，在交互上真的是糟糕的体验。

**Comment by GendSmith** [comment]
应该可以有更好的交互设计的😄

**Comment by simonguo** [comment]
如果有想到好的方式，欢迎随时交流。
