### ISSUE TITLE
固定头部和列的功能在移动设备上的支持

### ISSUE THREAD

**Issue by jxintang** [rsuite/rsuite-table#7]
RT，固定头部和列在移动设备的支持怎么样？

**Comment by simonguo** [comment]
@jxintang  `rsuite` 主要是真的企业后台管理系统做的一套组件，所有推荐还是在电脑上使用。 移动端我们没有做个特殊的优化处理，但是应该是可以正常访问的。

**Comment by simonguo** [comment]
@jxintang 在 rsuite-table@2.0.1-bata.1 已经支持
