### ISSUE TITLE
表格初始化时，如果数据为空，底部的滚动条无限长，并且最右边的固定列被挤掉了

### ISSUE THREAD

**Issue by GendSmith** [rsuite/rsuite-table#72]
![image](https://user-images.githubusercontent.com/22338894/54983713-52b34c80-4fe8-11e9-9e2c-67b46bfb609c.png)

**Comment by GendSmith** [comment]
background-color改成红色，是为了更好的显示最右边被挤掉的情况

**Comment by GendSmith** [comment]
我的配置是把最左边的一列fixed设置为true，最右边一列fixed为right

**Comment by simonguo** [comment]
你的代码是怎么写的？ 
最好可以提供一个示例:  https://codesandbox.io/s/lr16nr4jlm

**Comment by GendSmith** [comment]
这个涉及到表格的代码https://codesandbox.io/s/w0jjvnvw5
不过奇怪的是把代码拷贝到这里之后就无法复现了，rsuite是最新的3.8.1

**Comment by GendSmith** [comment]
方便的话我录屏复现一下bug

**Comment by GendSmith** [comment]
已解决。原因是使用了style = {{display:isShow?"block":"none"}}来控制是否显示表格。把这个去掉就好了。我换成了在render里面使用if-else，通过return不同的内容，选择是否显示表格
