### ISSUE TITLE
引入index.less 不生效

### ISSUE THREAD

**Issue by yyz841875845** [rsuite/rsuite-table#77]
请教，

**Comment by simonguo** [comment]
- 有报什么错误？ 
- 有配置 less-loader 吗？ 
- 你自己写的 less 生效吗？

**Comment by jchonc** [comment]
这里也是，直到找到老大reddit上面的回答直接用min.css才过。改了LESS吧。

**Comment by simonguo** [comment]
@yyz841875845   @jchonc  你怎么写的，你们的描述我无法判断什么问题，哪怕你说明详细，截图什么的。
能不能通过 https://codesandbox.io 添加一个示例说明一下

**Comment by jchonc** [comment]
https://github.com/jchonc/rsuite-table-less

我写了个基本空的，readme里有点解释，没有错误， 谢谢。

**Comment by simonguo** [comment]
@jchonc  首先检查一下你的css 是否引入到了页面。
我跑了一下看一下，在你html 的中插入了一个 style 标签，然后 class 已经被重命名，你是否应该好好检查一下自己的配置规则。

![image](https://user-images.githubusercontent.com/1203827/56432318-79228a00-62ff-11e9-904f-b184f511d3a7.png)

**Comment by jchonc** [comment]
谢谢提醒，发现原因，在 webpack.config.js里配置less的时候一定要把模块关掉，不然就会出现这种情况。

![Capture](https://user-images.githubusercontent.com/341949/56443763-f9c39500-62c3-11e9-91d7-286204cb5326.PNG)
