### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by jxintang** [rsuite/rsuite-table#8]
这个文件当中依赖了rsuite，但貌似npm install安装的时候并没有安装rsuite
版本2.0.0
```
./node_modules/rsuite-table/lib/TablePagination.js
Module not found: Can't resolve 'rsuite' in '/Users/tangduck/projects/rui/my-app4/node_modules/rsuite-table/lib'
```

**Comment by simonguo** [comment]
@jxintang  
![image](https://user-images.githubusercontent.com/1203827/30105416-1485fe4c-932b-11e7-92f0-d52d484f12d6.png)
需要安装的 rsuite 的, 我们是写在 `peerDependencies` 中

```js
"peerDependencies": {
    "react": "^0.14.9 || >=15.3.0",
    "react-dom": "^0.14.9 || >=15.3.0",
    "rsuite": ">=1.0.0"
  },
```

**Comment by jxintang** [comment]
@simonguo 
但是是readme中写的是
`npm i rsuite-table --save`

**Comment by simonguo** [comment]
@jxintang  感谢，我调整一下！
