### ISSUE TITLE
可以考虑增加选择框功能吗？

### ISSUE THREAD

**Issue by woohs** [rsuite/rsuite-table#80]
希望增加类似下图的选择框功能接口，这种多选的场景应该很常见。

![image](https://user-images.githubusercontent.com/31387031/57500420-eed5b080-7315-11e9-9889-662ed2671806.png)

**Comment by simonguo** [comment]
这是一个自定义列的功能
![image](https://user-images.githubusercontent.com/1203827/57502785-dc607480-731f-11e9-8a4a-5fa22846ce55.png)

**Comment by woohs** [comment]
好的，谢谢！已经参照官网范例，实现功能！
另外提一个小bug，官网范例里的程序有个console打印一个不存在的变量：
![image](https://user-images.githubusercontent.com/31387031/57506497-8a731b00-732e-11e9-8fc2-831972f2594d.png)
![image](https://user-images.githubusercontent.com/31387031/57506536-a5458f80-732e-11e9-9090-8816c919151c.png)

**Comment by simonguo** [comment]
谢谢，如果有发现文档有其他类似问题，也可以点击右上角编辑按钮，修改后给我们提 PR
![image](https://user-images.githubusercontent.com/1203827/57507047-35380900-7330-11e9-8690-846d0bfc971a.png)

**Comment by woohs** [comment]
好的
