### ISSUE TITLE
单独引入rsuite-table库，没有分页功能吗

### ISSUE THREAD

**Issue by woohs** [rsuite/rsuite-table#81]
这个单独引入，是没有包含分页组件吗，我在引入的时候，报错了。
`import { Table, Column, HeaderCell, Cell, Pagination } from 'rsuite-table';`

**Comment by simonguo** [comment]
`rsuite-table` 默认不包含分页组件， 如果需要使用分页组件需要安装 `rsuite`

**Comment by woohs** [comment]
我看现在的官网例程是有从table引入pagination组件，不知道是不是 `rsuite-table` 已经包含分页组件了？
官网table例程：
```
import { Table } from 'rsuite';

const { Column, HeaderCell, Cell, Pagination } = Table;
```

**Comment by simonguo** [comment]
rsuite-table 没有，这个 Pagination 是在rsuite中实现的
