### ISSUE TITLE
功能请求: 是否有rowspan行合并的功能？

### ISSUE THREAD

**Issue by aidening** [rsuite/rsuite-table#83]

**Comment by BarretL** [comment]
I would like to ask if rsuite-table supports cell merging on rows.

**Comment by BarretL** [comment]
目前我需要动态的合并行上的单元格，但是我在您提供的API当中没有看到rowspan这个属性，请问rsuite-table这个组件是否支持行上的单元格合并呢

**Comment by simonguo** [comment]
只支持列合并，不支持行合并
