### ISSUE TITLE
Question | Table Filter/Search

### ISSUE THREAD

**Issue by ShawnYcx** [rsuite/rsuite-table#84]
How would one go about building a filter by row or search?

**Comment by simonguo** [comment]
If you use the `rsuite` component library, you can customize a `<TableToolbar>`.

https://rsuitejs.com/design/index.html#artboard65

![image](https://user-images.githubusercontent.com/1203827/58925110-e89ded00-8778-11e9-849c-f656fba5ed8c.png)

**Comment by diez-esteban** [comment]
Hi  ShawnYcx, did you manage to create / setup a toolbar to have filtering capabilities on rsuite/Table?
I'm working on a project where it'd be great to use that component. That's the only key feature that I see it's missing. Thank you.

**Comment by jbuddha** [comment]
Not sure how to use it. Is TableToolbar deprecated? Can't find it anymore.

**Comment by hereischen** [comment]
你好 @simonguo 
https://rsuitejs.com/design/default/index.html#artboard74  这个链接已经404，
请问`<TableToolbar>`是需要自己写一个吗？

**Comment by simonguo** [comment]
@hereischen  新的设计稿地址 https://rsuitejs.com/design/default/index.html#s83 。  TableToolbar 需要你自己实现。

**Comment by genefever** [comment]
@simonguo I can't seem to access the design draft address https://rsuitejs.com/design/default/index.html#s83, do you have an updated link?

**Comment by simonguo** [comment]
@genefever @hereischen  Please visit the following link.
https://rsuitejs.com/design/default/#s83

**Comment by PiousVenom** [comment]
Is there documentation on this feature? I can't seem to find it anywhere.

**Comment by emrecoban** [comment]
@simonguo How can I use it?
