### ISSUE TITLE
字体显示模糊问题

### ISSUE THREAD

**Issue by woohs** [rsuite/rsuite-table#87]
列表里面的字体，都是同样的字体和样式，但是一行模糊一行正常，这是什么问题？
![image](https://user-images.githubusercontent.com/31387031/60955227-ff64d000-a332-11e9-8d1f-40e6844f3ce8.png)

**Comment by hiyangguo** [comment]
@woohs 你换个显示器试过么？

**Comment by woohs** [comment]
> @woohs 你换个显示器试过么？

试过了，会出现一样的问题，

**Comment by hiyangguo** [comment]
@woohs 能提供一下 Demo 么 
[https://codesandbox.io](https://codesandbox.io/s/k9v972q3lr?from-embed)

**Comment by woohs** [comment]
实在抱歉，现在不能复现问题了，我在观察一下吧

**Comment by simonguo** [comment]
类似问题： https://github.com/rsuite/rsuite-table/issues/98
