### ISSUE TITLE
[violation] requestAnimationFrame 

### ISSUE THREAD

**Issue by ShawnYcx** [rsuite/rsuite-table#91]
Hi, I'm using rsuite-table with my React application. I'm using the virtualized flag to display 10 to 60,000 rows of data. Here's the issue I'm facing, every time I scroll through the list of data on the table, it seems to be causing a requestAnimationFrame violation. Also, this might be what's causing my app's fps to hover only around 13 - 16fps on table scroll.

<img width="748" alt="Screen Shot 2019-08-12 at 4 25 30 PM" src="https://user-images.githubusercontent.com/7292742/62899916-702a4e00-bd1e-11e9-8e28-b1ff8a192d9a.png">

Is there a solution on this? Am I missing something critical on how it should be used?

More info on my data table:
- 11 Columns
- 10 - 60,000 Rows
- virtualized={true}
- height={500}
- 150width on all columns
- bordered 
- cellBordered 
- headerHeight={80}

On: 
- Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- Mac

**Comment by ronnie152147** [comment]
same issue here. Getting low FPS when I got around few thousands of data

**Comment by simonguo** [comment]
Please upgrade to the latest rsuite-table.
This issue will be closed, if you have other needs, please open a new one.
