### ISSUE TITLE
translate3d & backface-visibility 导致字体模糊，希望切换成transform: translateX;

### ISSUE THREAD

**Issue by piLurk** [rsuite/rsuite-table#98]

**Comment by piLurk** [comment]
在chrome (76.0.3809.132)复现。
下面的链接阐述了这一问题：
http://blog.codingplayboy.com/2016/11/27/css3_transform/

**Comment by piLurk** [comment]
![image](https://user-images.githubusercontent.com/25706123/65383921-508b3a00-dd4e-11e9-89e9-b6c78d74e9d4.png)
似乎是在调试页面页面选择了这个元素，然后滚动时才能复现。chrome这个GPU加速好迷呀。。

**Comment by simonguo** [comment]
translate3d 主要是为了让滚动更流畅， 这个问题，我可以做一个配置，用于启用和关闭 translate3d。

**Comment by simonguo** [comment]
使用最新版本：
```
npm i rsuite-table@latest
```

关闭 translate3d
```
<Table translate3d={false} />
```
